#!/usr/bin/env bash
# TEMPLATE FILE — @@REPO_NAME@@ commit script
# Source of truth: jarvis-standards/scripts/_templates/commit_core.template.sh
# Propagated to:   @@REPO_PATH@@/scripts/@@COMMIT_SCRIPT_NAME@@
#
# Unified commit script for JARVIS repos. Implements ADR-0005:
#   - Q1 coordination model — humans merge anywhere, agents always branch
#   - Q2 provenance — uniform git author + X-Machine and AI-* trailers
#   - Q3 branch namespace — feature/* humans, claude-code/* agents
#
# Trait switches (set by propagate.config):
#   @@HAS_BRANCH_SAFETY@@   — true: B-trait, enforce DEBT-027 + agent-must-branch
#   @@HAS_FANOUT@@          — true: F-trait, SSH-fan-out to @@FANOUT_NODES@@
#   @@HAS_UI_BUILD@@        — true: run npm build in ui/ before commit
#   @@FANOUT_NODES@@        — space-separated list (e.g. "brain gateway endpoint")
#   @@COMMIT_SCRIPT_NAME@@  — generated script name for self-reference
#
# Usage (human):
#   bash @@COMMIT_SCRIPT_NAME@@ "commit message"
#
# Usage (agent — Claude Code, forge):
#   JARVIS_AGENT=claude-code JARVIS_MODEL=claude-opus-4-7 \
#       bash @@COMMIT_SCRIPT_NAME@@ "commit message"
#
# Skip flags (F-trait only):
#   JARVIS_SKIP_BRAIN=1   bash @@COMMIT_SCRIPT_NAME@@ "msg"
#   JARVIS_SKIP_GATEWAY=1 bash @@COMMIT_SCRIPT_NAME@@ "msg"
#   etc.

set -uo pipefail

# ---------- Constants ----------
REPO_PATH="@@REPO_PATH@@"
REPO_NAME="@@REPO_NAME@@"
MAIN_BRANCH="@@MAIN_BRANCH@@"
COMMIT_SCRIPT_NAME="@@COMMIT_SCRIPT_NAME@@"
HAS_FANOUT="@@HAS_FANOUT@@"
HAS_BRANCH_SAFETY="@@HAS_BRANCH_SAFETY@@"
HAS_UI_BUILD="@@HAS_UI_BUILD@@"
FANOUT_NODES="@@FANOUT_NODES@@"

# ANSI colors
C_RED=$'\033[0;31m'
C_YELLOW=$'\033[1;33m'
C_GREEN=$'\033[0;32m'
C_CYAN=$'\033[0;36m'
C_BOLD=$'\033[1m'
C_RESET=$'\033[0m'

START_TIME="$(date +%s)"

# ---------- Args ----------
COMMIT_MSG="${1:-}"
if [ -z "$COMMIT_MSG" ]; then
    echo "${C_RED}USAGE: $COMMIT_SCRIPT_NAME \"commit message\"${C_RESET}" >&2
    exit 1
fi

# ---------- Helpers ----------
step()  { echo "${C_BOLD}Step $1:${C_RESET} $2"; }
ok()    { echo "  ${C_GREEN}✓${C_RESET} $1"; }
warn()  { echo "  ${C_YELLOW}⚠${C_RESET} $1" >&2; }
fail()  { echo "  ${C_RED}✗${C_RESET} $1" >&2; }
die()   { fail "$1"; echo; echo "${C_RED}${C_BOLD}ABORTED${C_RESET}"; exit 1; }

# ---------- Detect machine ----------
detect_machine() {
    local hn
    hn="$(hostname -s 2>/dev/null || hostname)"
    case "$hn" in
        *air*|*Air*)              echo "air" ;;
        *brain*|*Brain*)          echo "brain" ;;
        *gateway*|*Gateway*)      echo "gateway" ;;
        *endpoint*|*Endpoint*)    echo "endpoint" ;;
        *sandbox*|*Sandbox*)      echo "sandbox" ;;
        *forge*|*Forge*)          echo "sandbox" ;;  # legacy hostname pre-2026-04-28
        *)                        echo "unknown" ;;
    esac
}
MACHINE="$(detect_machine)"

# ---------- Detect agent context ----------
JARVIS_AGENT="${JARVIS_AGENT:-}"
JARVIS_MODEL="${JARVIS_MODEL:-}"
IS_AGENT=false
if [ -n "$JARVIS_AGENT" ]; then
    IS_AGENT=true
fi

# ---------- Banner ----------
echo "${C_CYAN}${C_BOLD}$COMMIT_SCRIPT_NAME${C_RESET}  ($REPO_NAME on $MACHINE)"
echo "  Subject:    $COMMIT_MSG"
if [ "$IS_AGENT" = "true" ]; then
    echo "  Agent:      $JARVIS_AGENT${JARVIS_MODEL:+ ($JARVIS_MODEL)}"
fi
echo

cd "$REPO_PATH" || die "Cannot cd to $REPO_PATH"

# ---------- Step 1: Pre-flight ----------
step 1 "Pre-flight"

# Source env files (best effort)
for envfile in "$HOME/jarvis/infra/env/.node_addresses" "$HOME/jarvis/.secrets" "$HOME/.secrets"; do
    if [ -f "$envfile" ]; then
        # shellcheck disable=SC1090
        . "$envfile" 2>/dev/null || warn "failed to source $envfile"
    fi
done

# Verify identifiable machine
if [ "$MACHINE" = "unknown" ]; then
    die "Cannot determine machine identity from hostname: $(hostname -s)"
fi
ok "Machine: $MACHINE"

# B-trait: branch-safety enforcement (DEBT-027 + Q1 from ADR-0005)
CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
if [ "$HAS_BRANCH_SAFETY" = "true" ]; then
    # Hard rule: agents may never commit to main directly
    if [ "$IS_AGENT" = "true" ] && [ "$CURRENT_BRANCH" = "$MAIN_BRANCH" ]; then
        die "Agent ($JARVIS_AGENT) cannot commit directly to $MAIN_BRANCH branch. Per ADR-0005 §4.3: use claude-code/<purpose>/<topic> branch."
    fi
    # Soft rule: humans on non-Air machines on main get a warning (Q1 allows it but flags it)
    if [ "$MACHINE" != "air" ] && [ "$IS_AGENT" = "false" ] && [ "$CURRENT_BRANCH" = "$MAIN_BRANCH" ]; then
        warn "Committing to $MAIN_BRANCH from $MACHINE (Q1 allows, but consider feature/* branch for audit trail)"
    fi
    ok "Branch-safety: $CURRENT_BRANCH"
fi

# Drift check (if check_sync.sh exists — generated by check_sync.template.sh)
if [ -x "$REPO_PATH/scripts/check_sync.sh" ]; then
    if "$REPO_PATH/scripts/check_sync.sh" --pre-commit >/dev/null 2>&1; then
        ok "Drift check: clean"
    else
        warn "Drift check reported issues — running with full output"
        "$REPO_PATH/scripts/check_sync.sh" --pre-commit || die "Drift check failed"
    fi
fi

echo

# ---------- Step 2: Lint ----------
step 2 "Lint"

if [ -f "$REPO_PATH/scripts/_lib/ruff_detect.sh" ]; then
    # shellcheck disable=SC1091
    . "$REPO_PATH/scripts/_lib/ruff_detect.sh"
    if ! detect_ruff; then
        warn "ruff not found in venv or PATH — skipping lint"
    else
        if "$RUFF" check . >/dev/null 2>&1; then
            ok "ruff check: clean"
        else
            "$RUFF" check . || die "ruff check failed"
        fi
        if "$RUFF" format --check . >/dev/null 2>&1; then
            ok "ruff format: clean"
        else
            warn "ruff format would make changes:"
            "$RUFF" format --check . || die "ruff format check failed"
        fi
    fi
else
    warn "scripts/_lib/ruff_detect.sh missing — skipping lint (propagate it from jarvis-standards)"
fi

echo

# ---------- Step 3: UI build (optional) ----------
if [ "$HAS_UI_BUILD" = "true" ] && [ -d "$REPO_PATH/ui" ]; then
    step 3 "Build UI"
    cd "$REPO_PATH/ui" || die "Cannot cd to ui/"
    if npm run build >/dev/null 2>&1; then
        ok "UI build: succeeded"
    else
        echo "  ${C_RED}UI build failed — full output:${C_RESET}"
        npm run build || die "UI build failed"
    fi
    cd "$REPO_PATH" || die "Cannot return to repo path"
    echo
fi

# ---------- Step 4: Stage + commit ----------
step 4 "Stage + commit"

# Pre-flight: surface untracked files (alpha-style improvement, Session #09 list)
UNTRACKED="$(git status --porcelain | awk '/^\?\?/ { sub(/^\?\? */, ""); print }')"
if [ -n "$UNTRACKED" ]; then
    warn "Untracked files that will be staged:"
    echo "$UNTRACKED" | sed 's/^/    /'
    if [ -t 0 ]; then
        printf "  Continue? [y/N] "
        read -r reply
        case "$reply" in
            y|Y) ok "Proceeding" ;;
            *)   die "Aborted by user" ;;
        esac
    else
        warn "Non-TTY environment — proceeding without prompt (DEBT-043 known limitation)"
    fi
fi

git add -A

if git diff --cached --quiet; then
    warn "Nothing to commit"
    exit 0
fi

# Build trailer block per ADR-0005 §2.2
TRAILER_BLOCK="X-Machine: $MACHINE"
if [ "$IS_AGENT" = "true" ]; then
    TRAILER_BLOCK="$TRAILER_BLOCK
AI-Agent: $JARVIS_AGENT"
    if [ -n "$JARVIS_MODEL" ]; then
        TRAILER_BLOCK="$TRAILER_BLOCK
AI-Model: $JARVIS_MODEL"
    fi
fi

# Compose full message: subject + blank + trailer block
COMMIT_FULL_MSG="$(cat <<EOF
$COMMIT_MSG

$TRAILER_BLOCK
EOF
)"

git commit -m "$COMMIT_FULL_MSG" >/dev/null || die "git commit failed"
COMMIT_HASH="$(git rev-parse --short HEAD)"
ok "Committed: $COMMIT_HASH"

# Verify trailer parsed correctly under git's own parser
PARSED="$(git log -1 --format=%B | git interpret-trailers --parse 2>/dev/null || true)"
if echo "$PARSED" | grep -q "^X-Machine: $MACHINE"; then
    ok "Trailer parsed: X-Machine: $MACHINE"
    if [ "$IS_AGENT" = "true" ]; then
        if echo "$PARSED" | grep -q "^AI-Agent: $JARVIS_AGENT"; then
            ok "Trailer parsed: AI-Agent: $JARVIS_AGENT"
        else
            warn "AI-Agent trailer not parsed — check commit body manually"
        fi
    fi
else
    warn "X-Machine trailer parsing failed — manual check: git log -1 --format=%B | git interpret-trailers --parse"
fi

echo

# ---------- Step 5: Push ----------
step 5 "Push"

CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"

# Defense in depth: re-check before push (already caught at Step 1, this is belt-and-suspenders)
if [ "$HAS_BRANCH_SAFETY" = "true" ] && [ "$IS_AGENT" = "true" ] && [ "$CURRENT_BRANCH" = "$MAIN_BRANCH" ]; then
    die "Internal: agent on $MAIN_BRANCH at push time — Step 1 should have caught this"
fi

# Pull --rebase to integrate any concurrent changes (ignore failures — branch may be brand new)
git pull --rebase origin "$CURRENT_BRANCH" 2>/dev/null || true

if git push -u origin "$CURRENT_BRANCH" 2>&1 | tail -5; then
    ok "Pushed: $CURRENT_BRANCH"
else
    die "Push failed"
fi

# If agent on a feature branch, surface the PR URL
if [ "$IS_AGENT" = "true" ] && [ "$CURRENT_BRANCH" != "$MAIN_BRANCH" ]; then
    echo "  Open PR: https://github.com/kphaas/$REPO_NAME/pull/new/$CURRENT_BRANCH"
fi

echo

# ---------- Step 6: Fan-out (F-trait only) ----------
if [ "$HAS_FANOUT" = "true" ] && [ -n "$FANOUT_NODES" ]; then
    step 6 "Fan-out to nodes ($FANOUT_NODES)"

    FANOUT_SUCCEEDED=""
    for node in $FANOUT_NODES; do
        # Skip self
        if [ "$node" = "$MACHINE" ]; then
            warn "Skipping $node (current machine)"
            continue
        fi

        # JARVIS_SKIP_<NODE> override
        skip_var="JARVIS_SKIP_$(echo "$node" | tr '[:lower:]' '[:upper:]')"
        eval "skip_val=\"\${${skip_var}:-}\""
        if [ -n "$skip_val" ]; then
            warn "Skipping $node ($skip_var=$skip_val)"
            continue
        fi

        # SSH with halt-on-fail (TD-88 pattern)
        if ssh -o ServerAliveInterval=30 -o ConnectTimeout=10 \
               -o StrictHostKeyChecking=no \
               "$node" "cd $REPO_PATH && git pull origin $CURRENT_BRANCH" \
               </dev/null 2>&1 | tail -3; then
            ok "$node: pulled"
            FANOUT_SUCCEEDED="$FANOUT_SUCCEEDED $node"
        else
            fail "$node: pull failed"
            echo "  ${C_RED}Fan-out halted. Already-pulled nodes:${C_RESET}$FANOUT_SUCCEEDED"
            echo "  ${C_RED}Manual recovery: pull this branch on remaining nodes, or rollback via git revert${C_RESET}"
            die "Fan-out halt-on-fail at $node"
        fi
    done

    ok "Fan-out complete:$FANOUT_SUCCEEDED"
    echo
fi

# ---------- Summary ----------
END_TIME="$(date +%s)"
DURATION=$((END_TIME - START_TIME))

echo "${C_CYAN}${C_BOLD}$COMMIT_SCRIPT_NAME — success${C_RESET}"
echo "  Hash:       $COMMIT_HASH"
echo "  Branch:     $CURRENT_BRANCH"
echo "  Machine:    $MACHINE"
if [ "$IS_AGENT" = "true" ]; then
    echo "  Agent:      $JARVIS_AGENT${JARVIS_MODEL:+ / $JARVIS_MODEL}"
fi
if [ "$HAS_FANOUT" = "true" ] && [ -n "$FANOUT_NODES" ]; then
    echo "  Fan-out:    $FANOUT_NODES"
fi
echo "  Duration:   ${DURATION}s"

exit 0
